### PR TITLE
Add a Legend control to the project

### PR DESCRIPTION
**Pull request by ehunter-usgs**
This allows for images or html to be added to a control that expands/collapses on hover/click.

### CODE REVIEW

**Comment by ehunter-usgs** [comment]
legend-control-screenshots

The image above shows what it could look like when integrated with the interactive map on the event pages. There should be a fourth screenshot showing what it would look like when passing in HTML markup, but I forgot to screenshot it. See the examples in the app for an example.

**Comment by ehunter-usgs** [comment]
screen shot 2017-05-18 at 5 47 34 pm

This is what the **expanded** control would look like earthquake-latest-earthquakes

**Comment by llastowka-usgs** [comment]
I like the middle one.

**Comment by ehunter-usgs** [comment]
@llastowka-usgs I agree. We could add headers if we had more than one legend, but until we add multiple legends that seems unnecessary.

**Comment by emartinez-usgs** [comment]
I spoke with @ehunter-usgs to clarify some use-cases and he will continue work on this pull request prior to moving forward.

**Pull request merged**
